//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabPasswords.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PasswordsDropboxFolder {
            get {
                return ((string)(this["PasswordsDropboxFolder"]));
            }
            set {
                this["PasswordsDropboxFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ActiveUserID {
            get {
                return ((int)(this["ActiveUserID"]));
            }
            set {
                this["ActiveUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ActiveItemTypeID {
            get {
                return ((int)(this["ActiveItemTypeID"]));
            }
            set {
                this["ActiveItemTypeID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedItems {
            get {
                return ((string)(this["SelectedItems"]));
            }
            set {
                this["SelectedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MinPasswordLength {
            get {
                return ((int)(this["MinPasswordLength"]));
            }
            set {
                this["MinPasswordLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int MaxPasswordLength {
            get {
                return ((int)(this["MaxPasswordLength"]));
            }
            set {
                this["MaxPasswordLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxNumberOfBackupFiles {
            get {
                return ((int)(this["MaxNumberOfBackupFiles"]));
            }
            set {
                this["MaxNumberOfBackupFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("840, 800")]
        public global::System.Drawing.Size frmMainSize {
            get {
                return ((global::System.Drawing.Size)(this["frmMainSize"]));
            }
            set {
                this["frmMainSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 325")]
        public global::System.Drawing.Point frmMainLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmMainLocation"]));
            }
            set {
                this["frmMainLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmMainWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmMainWindowState"]));
            }
            set {
                this["frmMainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("710, 500")]
        public global::System.Drawing.Size frmChangePasswordSize {
            get {
                return ((global::System.Drawing.Size)(this["frmChangePasswordSize"]));
            }
            set {
                this["frmChangePasswordSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 325")]
        public global::System.Drawing.Point frmChangePasswordLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmChangePasswordLocation"]));
            }
            set {
                this["frmChangePasswordLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmChangePasswordState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmChangePasswordState"]));
            }
            set {
                this["frmChangePasswordState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("710, 410")]
        public global::System.Drawing.Size frmGetPasswordSize {
            get {
                return ((global::System.Drawing.Size)(this["frmGetPasswordSize"]));
            }
            set {
                this["frmGetPasswordSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 325")]
        public global::System.Drawing.Point frmGetPasswordLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmGetPasswordLocation"]));
            }
            set {
                this["frmGetPasswordLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmGetPasswordState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmGetPasswordState"]));
            }
            set {
                this["frmGetPasswordState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("416, 423")]
        public global::System.Drawing.Size frmRandomPasswordDialogSize {
            get {
                return ((global::System.Drawing.Size)(this["frmRandomPasswordDialogSize"]));
            }
            set {
                this["frmRandomPasswordDialogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 325")]
        public global::System.Drawing.Point frmRandomPasswordDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmRandomPasswordDialogLocation"]));
            }
            set {
                this["frmRandomPasswordDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmRandomPasswordDialogState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmRandomPasswordDialogState"]));
            }
            set {
                this["frmRandomPasswordDialogState"] = value;
            }
        }
    }
}
